### ISSUE TITLE
No previous notification found

### ISSUE THREAD

**Issue by moreirawebmaster** [emanuel-braz/deeplink#5]
Hello.

Thanks to sharing this plugin.

Man there message below is showing when press Push Notification
![image](https://github.com/emanuel-braz/deeplink/assets/1142139/82c23593-9170-4b05-9bba-7c05f21b3e42)

Khow use this feature?

No previous notification found

**Comment by emanuel-braz** [comment]
This is happening because you are trying to run the last notification from history, but you didn't have history yet. 

Follow this instructions, and edit the created file as you want
<img width="446" alt="image" src="https://github.com/emanuel-braz/deeplink/assets/3827308/3bcdeb3d-56e2-4571-971d-c3ecfad558d5">

<img width="587" alt="image" src="https://github.com/emanuel-braz/deeplink/assets/3827308/e422a09b-aec7-42bf-8b94-907bf68053bb">
